-- ==========================================================
-- VISITOR COUNTER DATABASE SCHEMA FOR SUPABASE (SIMPLIFIED)
-- Run these queries in your Supabase SQL Editor
-- ==========================================================

-- Clean up and drop all previous tracking tables, indexes, and publications
DROP TABLE IF EXISTS public.visitor_sessions CASCADE;
DROP TABLE IF EXISTS public.unique_visitors CASCADE;
DROP TABLE IF EXISTS public.visitor_counts CASCADE;

-- Create visitor_counts table
CREATE TABLE public.visitor_counts (
    id INT PRIMARY KEY,
    count INT NOT NULL DEFAULT 0
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.visitor_counts ENABLE ROW LEVEL SECURITY;

-- Policy to allow anonymous reading of the counts
CREATE POLICY "Allow public select" ON public.visitor_counts
    FOR SELECT TO anon, authenticated USING (true);


-- Insert initial row (starts at 1420, feel free to change this start value!)
INSERT INTO public.visitor_counts (id, count) VALUES (1, 1420)
ON CONFLICT (id) DO NOTHING;


-- Create thread-safe RPC function to increment the visitor count
CREATE OR REPLACE FUNCTION public.increment_visitor_count()
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  UPDATE public.visitor_counts
  SET count = count + 1
  WHERE id = 1;
END;
$$;

-- Grant execute permissions to anonymous/public users
GRANT EXECUTE ON FUNCTION public.increment_visitor_count() TO anon, authenticated;


-- ==========================================
-- ACHIEVEMENTS SCHEMAS (CAMPS & ALUMNI)
-- ==========================================

-- 1. Create nss_camps table
CREATE TABLE IF NOT EXISTS public.nss_camps (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    camp_type TEXT NOT NULL, -- 'NIC', 'Pre-RD', 'Adventure', 'Youth Festival', 'Other'
    volunteers TEXT NOT NULL,
    location TEXT NOT NULL,
    po_name TEXT NOT NULL,
    year TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.nss_camps ENABLE ROW LEVEL SECURITY;

-- Policies for nss_camps
CREATE POLICY "Allow public select on camps" ON public.nss_camps FOR SELECT USING (true);
CREATE POLICY "Allow admin write on camps" ON public.nss_camps FOR ALL TO authenticated USING (true) WITH CHECK (true);


-- 2. Create nss_alumni table
CREATE TABLE IF NOT EXISTS public.nss_alumni (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    passing_year TEXT NOT NULL,
    current_position TEXT NOT NULL,
    organization TEXT NOT NULL,
    description TEXT NOT NULL,
    photo_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.nss_alumni ENABLE ROW LEVEL SECURITY;

-- Policies for nss_alumni
CREATE POLICY "Allow public select on alumni" ON public.nss_alumni FOR SELECT USING (true);
CREATE POLICY "Allow admin write on alumni" ON public.nss_alumni FOR ALL TO authenticated USING (true) WITH CHECK (true);
